project:
  type: website
  output-dir: docs

website:
  title: "Hjördis Aho's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: test.qmd
        text: Test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

